apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-configmap
data:
  MONGO_URI: "mongodb://mongodb-service:27017/hospital_management"
  PORT: "5000"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: hospital-secret
type: Opaque
stringData:                       # stringData = plain text, k8s encodes it for you
  SESSION_SECRET: "hospital-secret-key-2026"
  JWT_SECRET: "jwt-hospital-2026"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin@123"